### ISSUE TITLE
VS986 keeps dialing even after RIL voice connection using AOSiP-9.0-Pizza-H811 ROM

### ISSUE THREAD

**Issue by tullyp** [ANDROID2468/RilVoiceFix#1]
Hi,
Been using this script with @SteadfasterX 16.0 Pie ROM successfully.

 This above referenced H811 ROM  by @aoleary works great with Verizon VS986 (even RIL service) though all build.prop refers to H-811.  Had to change "ro.product.model= " from LGH811 to LGVS986 to get it to see phone and run your script, but won't stop dialing even after gets service.  

I know you are no longer using G4 per other posts, but I don't know how to read script well enough to tell what makes it stop after service is initiated.
@tullyp

**Comment by ANDROID2468** [comment]
> Hi,
> Been using this script with @steadfasterX 16.0 Pie ROM successfully.
> 
> This above referenced H811 ROM by @aoleary works great with Verizon VS986 (even RIL service) though all build.prop refers to H-811. Had to change "ro.product.model= " from LGH811 to LGVS986 to get it to see phone and run your script, but won't stop dialing even after gets service.
> 
> I know you are no longer using G4 per other posts, but I don't know how to read script well enough to tell what makes it stop after service is initiated.
> @tullyp

hi tullyp,
I need a log.
do you have Maid (FWUL) or any Linux//mac?
please run this command  at first boot until your phone makes 3 calls then do Ctrl+c on the keyboard  and post the getprop.log file (it's in the directory that you run the command from.)

make sure USB debugging is enabled and select usb file transfer when you run the command

` while :; do adb shell getprop |grep sim.operator.alpha >> getprop.log && adb shell getprop | grep gsm >> getprop.log; sleep 1; done
`

**Comment by tullyp** [comment]
Will do, thxOn Dec 27, 2020 4:58 PM, ANDROID2468 <notifications@github.com> wrote:

Hi,
Been using this script with @steadfasterX 16.0 Pie ROM successfully.
This above referenced H811 ROM by @aoleary works great with Verizon VS986 (even RIL service) though all build.prop refers to H-811. Had to change "ro.product.model= " from LGH811 to LGVS986 to get it to see phone and run your script, but won't stop dialing even after gets service.
I know you are no longer using G4 per other posts, but I don't know how to read script well enough to tell what makes it stop after service is initiated.
@tullyp

hi tullyp,
I need a log.
do you have Maid (FWUL) or any Linux//mac?
please run this command  at first boot until your phone makes 3 calls then do Ctrl+c on the keyboard  and post the getprop.log file (it's in the directory that you run the command from.)
make sure USB debugging is enabled and select usb file transfer when you run the command
while :; do adb shell getprop |grep sim.operator.alpha >> getprop.log && adb shell getprop | grep gsm >> getprop.log; sleep 1; done

**Comment by tullyp** [comment]
Hi @ANDROID2468,See getprop.log attached. BTW, I have G6 android 7 port forwarded ROM from T-Mobile H811 with working Verizon data on my g4 but can't get cell HD voice working (yet).  It is connecting to the verizon HD AWS LTE (XLTE), but can't get network setting to work on CDMA Verizon.Can send you more info if interested.@tullypOn Dec 27, 2020 4:58 PM, ANDROID2468 <notifications@github.com> wrote:

Hi,
Been using this script with @steadfasterX 16.0 Pie ROM successfully.
This above referenced H811 ROM by @aoleary works great with Verizon VS986 (even RIL service) though all build.prop refers to H-811. Had to change "ro.product.model= " from LGH811 to LGVS986 to get it to see phone and run your script, but won't stop dialing even after gets service.
I know you are no longer using G4 per other posts, but I don't know how to read script well enough to tell what makes it stop after service is initiated.
@tullyp

hi tullyp,
I need a log.
do you have Maid (FWUL) or any Linux//mac?
please run this command  at first boot until your phone makes 3 calls then do Ctrl+c on the keyboard  and post the getprop.log file (it's in the directory that you run the command from.)
make sure USB debugging is enabled and select usb file transfer when you run the command
while :; do adb shell getprop |grep sim.operator.alpha >> getprop.log && adb shell getprop | grep gsm >> getprop.log; sleep 1; done

**Comment by ANDROID2468** [comment]
> Hi @ANDROID2468,See getprop.log attached. BTW, I have G6 android 7 port forwarded ROM from T-Mobile H811 with working Verizon data on my g4 but can't get cell HD voice working (yet).  It is connecting to the verizon HD AWS LTE (XLTE), but can't get network setting to work on CDMA Verizon.Can send you more info if interested.@tullypOn Dec 27, 2020 4:58 PM, ANDROID2468 <notifications@github.com> wrote: Hi, Been using this script with @steadfasterX 16.0 Pie ROM successfully. This above referenced H811 ROM by @aoleary works great with Verizon VS986 (even RIL service) though all build.prop refers to H-811. Had to change "ro.product.model= " from LGH811 to LGVS986 to get it to see phone and run your script, but won't stop dialing even after gets service. I know you are no longer using G4 per other posts, but I don't know how to read script well enough to tell what makes it stop after service is initiated. @tullyp hi tullyp, I need a log. do you have Maid (FWUL) or any Linux//mac? please run this command at first boot until your phone makes 3 calls then do Ctrl+c on the keyboard and post the getprop.log file (it's in the directory that you run the command from.) make sure USB debugging is enabled and select usb file transfer when you run the command while :; do adb shell getprop |grep sim.operator.alpha >> getprop.log && adb shell getprop | grep gsm >> getprop.log; sleep 1; done —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ANDROID2468** [comment]
@tullyp 
nope I don't see the log, 
try pasebin https://pastebin.com/ if github wont let you upload it

BTW just to let you know that I started to work on  on potato OS 9  again. I was able to fix the long boot times, now I'm working on applying security patches to it.

**Comment by tullyp** [comment]
@ANDROID2468,I attached the file to this email to try again, but I have switched to AEX ROM now, and it works very well with your RILVoiceFix so don't worry about fixing  with AOSiP now for me.Looking forward to trying your latest Potato when it is available.  I'm watching XDA.Thanks,@tullypOn Jan 3, 2021 8:01 PM, ANDROID2468 <notifications@github.com> wrote:
@tullyp
nope I don't see the log,
try pasebin https://pastebin.com/ if github wont let you upload it
BTW just to let you know that I started to work on  on potato OS 9  again. I was able to fix the long boot times, now I'm working on applying security patches to it.

**Comment by steadfasterX** [comment]
> @ANDROID2468,I attached the file to this email to try again, but I have switched to AEX ROM now, and it works very well with your RILVoiceFix so don't worry about fixing  with AOSiP now for me.Looking forward to trying your latest Potato when it is available.  I'm watching XDA.Thanks,@tullypOn Jan 3, 2021 8:01 PM, ANDROID2468 <notifications@github.com> wrote: @tullyp nope I don't see the log, try pasebin https://pastebin.com/ if github wont let you upload it BTW just to let you know that I started to work on on potato OS 9 again. I was able to fix the long boot times, now I'm working on applying security patches to it. —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

I guess using Email for replying to a github comment does not attach any files

**Comment by ANDROID2468** [comment]
> @ANDROID2468,I attached the file to this email to try again, but I have switched to AEX ROM now, and it works very well with your RILVoiceFix so don't worry about fixing  with AOSiP now for me.Looking forward to trying your latest Potato when it is available.  I'm watching XDA.Thanks,@tullypOn Jan 3, 2021 8:01 PM, ANDROID2468 <notifications@github.com> wrote: @tullyp nope I don't see the log, try pasebin https://pastebin.com/ if github wont let you upload it BTW just to let you know that I started to work on on potato OS 9 again. I was able to fix the long boot times, now I'm working on applying security patches to it. —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

Nice, thanks!
